#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> [<subdomain>]
# function to query DNS information for a subdomain
domain_information() {
	local subdomain="$1"
	local domain="$2"
	local record_type
	local result

	result=$(dig "$subdomain.$domain" +short)

	# Check if the result is empty
	if [ -z "$result" ]; then
		echo "The subdomain $subdomain does not exist for $domain"
	else
		record_type=$(dig "$subdomain.$domain" | awk '/IN\s+A/ {print "A"}')
		echo "The subdomain $subdomain is a $record_type record and points to $result"
	fi
	}

# Check the number of command-line arguments
if [ $# -eq 1 ]; then
	# When only the domain argument is provided, query information for specific subdomains
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"; do
		domain_information "$subdomain" "$1"
    	done
elif [ $# -eq 2 ]; then
	# When both domain and subdomain arguments are provided, query info
	# for the specified subdomain
	domain_information "$2" "$1"
else
	echo "Usage: $0 <domain> [<subdomain>]"
fi
