#!/usr/bin/env bash
# function to query DNS information for a subdomain
query_dns() {
	local subdomain="$1"
	local domain="$2"

	# Use dig to query DNS information for the subdomain
	local result
	result=$(dig "$subdomain.$domain" +short)

	# Check if the result is empty
	if [ -z "$result" ]; then
		echo "The subdomain $subdomain does not exist for $domain"
	else
		local record_type
		record_type=$(dig "$subdomain.$domain" | awk '/IN\s+A/ {print $4}')
		echo "The subdomain $subdomain is a $record_type record and points to $result"
	fi
	}

# Check the number of command-line arguments
if [ $# -eq 1 ]; then
	# When only the domain argument is provided, query information for specific subdomains
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"; do
	    query_dns "$subdomain" "$1"
    	done
elif [ $# -eq 2 ]; then
	# When both domain and subdomain arguments are provided, query info
	# for the specified subdomain
	query_dns "$2" "$1"
else
	echo "Usage: $0 <domain> [<subdomain>]"
fi
