#!/usr/bin/env bash
# Transfer a file from our client to a server
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi;

# Check if 4 or more paramters are passed
if [ $# -ge 4 ]; then
    # Use scp to transfer the file to the user's home directory on
    # the server
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    # Use scp to transfer the file to the user's home directory on
    # the server without specifying a key
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
