#!/usr/bin/env bash
# Update package information and install nginx using apt-get with -y

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start

