#!/usr/bin/env bash

# Update package information
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create directories for web content and error pages
sudo mkdir -p /var/www/html /var/www/error

# Set permissions for web directories
sudo chmod -R 755 /var/www

# Create an index.html file with "Hello World!" content
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404 error page
echo "Ceci n'test pas une page" | sudo tee /var/www/html/404.html

# Define Nginx server configuration
server_config="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

# Create a new Nginx configuration file with the server_config content
echo "$server_config" | sudo tee /etc/nginx/sites-available/custom_header

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Test the Nginx configuration for errors
sudo nginx -t

# If the test is successful, reload Nginx to apply the changes
sudo systemctl reload nginx
