#!/usr/bin/env bash
# Installs, configures, and starts the load balancer

# Updates package information
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Define variables
DOMAIN_NAME='congojunior.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG="\
#--$DOMAIN_NAME-params-begin--
	backend $DOMAIN_NAME-backend
	balance roundrobin
	server 246763-web-01 34.237.91.196:80 check
	server 246763-web-02 3.89.146.172:80 check
frontend $DOMAIN_NAME-frontend
	bind *:80
	mode http
	default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

# Create the configuration files if they don't exist
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

# Check if HAProxy is enabled in the init file
if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
	sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
	echo 'ENABLED=1' >> $INIT_FILE
fi

# Check if the configuration for this domain exists and replace it
CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)
if [ "$CONFIG_WORDS" -gt 0 ]; then
	start_tkn="#--$DOMAIN_NAME-params-begin--"
	end_tkn="#--$DOMAIN_NAME-params-end--"
	a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	a=$((a - 1))
	b=$((b + 1))
	sed -i "$a,$b"d "$CONFIG_FILE"
fi

# Add the new configuration
echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE

# Start or restart HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
