#!/usr/bin/env bash
# This Bash script is used to ping an IP Address and display ping statistics

if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
