#!/usr/bin/env bash
# This script stops task #7 without kill or killall commands

pid=$(pgrep "7-highlander")
if [[ -n $pid ]]; then
	# Terminate the process by sending SIGTERM signal
	kill _SIGTERM "$pid"
else
	echo "Process not found"
fi
